### ISSUE TITLE
Wrapper Method

### ISSUE THREAD

**Issue by philippefutureboy** [egeozcan/ppipe#2]
I worked on a similar Pipe system a year and a half ago, and I must say, great job!
I compared the functionality of your Pipe versus mine for functionalities that might be of interest, and I came up with one that could be good - returning the pipe as a wrapper function.

From an example code of mine:

```js
function employeePipe() {
  return Pipe.build()
    .pipe(search)
    .map(x => {data: x, tag: x, search: x })
    .wrap();
}
```

So what happens above is that the pipe is built with a set of operations (search, then map), and then is returned as a function that can be reused. This can be really useful as you can pass the pipe around and use it like any other function. 

It is equivalent to

```js
function myPipe(data){
  ppipe(data)
  .pipe(add, 1)
  .pipe(double)
  .pipe(square)
  .pipe(divide, _, 8)
  .pipe(add, 1)();
}
```

Let me know what you think!

Cheers 🦄

**Comment by egeozcan** [comment]
My first issue! Thank you! With the new function syntax, I don't think this is a big problem:

```javascript
const buildPipe => (x) => ppipe(x)(someFn, _, "foo")(otherFn);
```

But of course, maybe I'm missing something and I'm open to your suggestions.

**Comment by philippefutureboy** [comment]
My pleasure :)

Fair point! Adding the wrap function at this point might not be as necessary anymore. Back then I was using early ES5, and arrow functions were not already available. Times have changed it seems :P 

Cheers!
