### ISSUE TITLE
Add coverage

### ISSUE THREAD

**Issue by fvictorio** [egeozcan/ppipe#3]
### Expected Behavior

After running `npm test`, you should be able to see the coverage of the code. This would make `ppipe` more trustworthy and would also help people that want to contribute (assuming that there are lines or branches not covered by the current tests). Awesome project btw :smiley: 

### Actual Behavior

No coverage directory.

### Steps to Reproduce the Problem

  1. Run `npm test`
  1. `ls`

**Comment by egeozcan** [comment]
Hi, thanks for the report. ppipe exports a single function so I could say the coverage is 100%, but of course, being explicit is better. I will add [nyc](https://github.com/istanbuljs/nyc). I was actually thinking about switching to ava to run all the tests parallel and nyc seems to be compatible with that as well.

**Comment by egeozcan** [comment]
Added in d6d4e9928dff3e1077bbe859e96c9e1dd7b980a8 . Could you please test?

**Comment by fvictorio** [comment]
Thanks for the quick response!

It works, but I'd suggest you add the HTML reporter:

```
	"scripts": {
		"test": "nyc --reporter=text --reporter=html node_modules/mocha/bin/mocha test"
	},
```

That way you get a `coverage` directory with an HTML report and you can see which lines/branches are not covered:

![image](https://user-images.githubusercontent.com/417134/31190333-2a4dafc6-a911-11e7-96fb-8facaa4f2e44.png)

**Comment by egeozcan** [comment]
I just committed some changes which bring code coverage to 100% :) I will try the html thingie now^^

**Comment by egeozcan** [comment]
@fvictorio The last coverage error which is "else path not taken" has made me find a potential bug on an edge case. Unlikely to happen but anyways... Fixing it now. Really glad that you suggested this, thank you!

**Comment by fvictorio** [comment]
Awesome! I'll try to use `ppipe` in some project and maybe I can give you more feedback.
